import type { Metadata } from 'next';
import './globals.css';
import { LayoutContent } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <LayoutContent className="antialiased">{children}</LayoutContent>
    </>
  );
}
