import type { Metadata } from 'next';
import './globals.css';
import { LayoutContent } from '@/components';
import { getGlobalSettings } from '@/sanity/lib/dataFetchers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getGlobalSettings();
  return (
    <>
      <LayoutContent
        header={settings?.header}
        footer={settings?.footer}
        className="antialiased"
      >
        {children}
      </LayoutContent>
    </>
  );
}
